### ISSUE TITLE
App Category parsing

### ISSUE THREAD

**Issue by mrahbar** [MarcelloLins/GooglePlayAppsCrawler#12]
Not realy an issue but I was wondering about that following line in PlayStoreParser:

https://github.com/MarcelloLins/GooglePlayAppsCrawler/blob/master/SharedLibrary/PlayStoreParser.cs#L109

It eliminates the category parsing in the above lines and also drops the NO_CATEGORY_FOUND fallback. Is that intended?

**Comment by MarcelloLins** [comment]
Hello there,

Thanks for checking in. ! 
No, that was not intended :)
I will have it fixed on the next commit, soon.
