### ISSUE TITLE
Args library suggestion

### ISSUE THREAD

**Issue by Zeioth** [MarcelloLins/GooglePlayAppsCrawler#14]
Hi Marcello, this library may interest you, since it's a much cleaner and easier way to deal with args. You can download it using NuGet. Regards.

Documentation: http://commandline.codeplex.com/
Compatibility: Windows, Mac, Linux.

**Comment by MarcelloLins** [comment]
Thanks a bunch ! I will give it a try ;) I always wondered if there was a better approach to things like this...there we are ! :)

**Comment by Zeioth** [comment]
Great! By the way, I just realized that commandline have been discontinued, so you may prefer mono.options instead.
Example: http://stackoverflow.com/a/2067916/2010764
