### ISSUE TITLE
WebUtilsLib.dll fails using MonoDevelop on linux

### ISSUE THREAD

**Issue by machado2** [MarcelloLins/GooglePlayAppsCrawler#21]
I observed this problem debugging the function CrawlCategory, in crawler.cs, line 281.
The server.Post function is returning an empty string, and 0 as the http status code.

I mentioned I am using MonoDevelop and Linux because I suppose you're not testing on those, but I can't know for sure if it's related to the problem.

**Comment by Zeioth** [comment]
I'm using mono develop alpha and i don't have this problem. An empty string usually means you are banned from playstore due to too many requests.

**Comment by MarcelloLins** [comment]
Hello @machado2  !

Yes, I have tested on Mono on a ubuntu server multiple times, and it worked wonders.

The only thing that may be a problem is if you modify the code to do multi-threading, since it breaks on some mono versions, because of specific kernel versions.

But as @Zeioth  said, yes, empty returns means you got blocked, basically.

**Comment by machado2** [comment]
Hello @MarcelloLins and @Zeioth,

Thanks for replying so quickly. I detected this problem in less than 1 min of running the program, and I can still open play.google.com on my browser, this 0 for http status code is very strange. I also opened the same URL that failed for webutilslib on my browser and it opened.

The only change I made in the program was the "ToolsVersion=12.0" in some .csproj files that was blocking monodevelop from loading. I am using the stock monodevelop from kubuntu 14.04. And my connection is an 10mbit ADSL.

I will test if my monodevelop has any https certificate issue.

**Comment by machado2** [comment]
I tested my installation using the stock System.Net.Webclient class, and confirmed my monodevelop has a problem with https certificates.

Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server

**Comment by machado2** [comment]
O comando abaixo importou os certificados raiz ssl do firefox e o meu monodevelop passou a funcionar com https, resolvendo o problema.

yes yes | mozroots --import

**Comment by MarcelloLins** [comment]
One last comment just for future reference:

Yes, you have to install the mozilla certificates, but there's also one thing you must do, depending on the kernel version of your Ubuntu OS and the Mono Version, which is to add this line of code to the project, in any place where it only gets executed once (in the start of the main function, for instance):

    ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;


This will basically tell the OS to not verify certificates (have in mind that this must be dangerous security-wise, but it works).

You can either do this, or, upgrade Mono to version 4.x and the kernel must be at least 3.13.0-44-generic

Here are the commands I use on a new ubuntu machine :

    ## Update everything!
    sudo apt-get check && sudo apt-get autoclean -y && sudo apt-get update -y && sudo apt-get   upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y  

    ## Install Mono 4.0
    sudo apt-get install mono-complete
    
    ## install latest valid kernel
    sudo apt-get install linux-image-3.13.0-44-generic -y
    
    ## remove invalid kernels
    sudo apt-get purge linux-image-3.13.0-53-generic linux-image-3.13.0-52-generic linux-image-3.13.0-51-generic  linux-image-3.13.0-49-generic linux-image-3.13.0-50-generic  linux-image-3.13.0-48-generic  linux-image-3.13.0-47-generic -y
    
    # reboot to use the older kernel
    sudo reboot
