### ISSUE TITLE
This is the new regex for crawler pagination.

### ISSUE THREAD

**Issue by Zeioth** [MarcelloLins/GooglePlayAppsCrawler#39]
To fix it, you only need to change this two lines in crawler.cs. As you can see I'm just changing \\42 for \\x22. Also, the last replace was useless so i deleted it. I don't have much time right now so if someone read this, please commit it. Thank you.

**OLD:** Regex pagTokenRegex = new Regex (@"GAEi+.+\:S\:.{11}\\42", RegexOptions.Compiled);
**NEW:** Regex pagTokenRegex = new Regex (@"GAEi+.+\:S\:.{11}\\x22", RegexOptions.Compiled);

**OLD:** string pagToken = rgxMatch.Value.Replace (":S:", "%3AS%3A").Replace("\\42", String.Empty).Replace(@"\\u003d", String.Empty);
**NEW:** string pagToken = rgxMatch.Value.Replace (":S:", "%3AS%3A").Replace("\\x22", String.Empty);

**Comment by MarcelloLins** [comment]
You are the best, @Zeioth  !

I will check it and test on my end.

Do you mind providing the file name and what tests failed on your end, that made you go against those regexes ?

**Comment by Zeioth** [comment]
The file is crawler.cs

Since some days ago, my crawler just stopped to be able to paginate until i changed that. Page 1 was parsed ok, it only failed on paginating. This is a frament of my code, but may be a bit different from MASTER branch.

```csharp
// Set reqData for the next request (using next page token)
rgxMatch = Constants.CRAWL_PAG_TOKEN.Match (response);
if (rgxMatch.Success) {
    thereIsPageToken = true;
    pagToken = rgxMatch.Value.Replace (":S:", "%3AS%3A")
                                                 .Replace ("\\x22", string.Empty);
    reqData = String.Format (Constants.CRAWL_POST_DATA, pagToken);
} else {
    thereIsPageToken = false;
    logger.Warn ("WARNING: Couldn't find page token in HTML code.");
}
```
